### ISSUE TITLE
Any update on release?

### ISSUE THREAD

**Issue by josephrocca** [AnkaChan/Gaia#1]
After seeing the videos of your algorithm I'm excited to play around with it - specifically I think it would be cool to try creating a demo of it working on the web using Wasm and WebGPU. So I'm wondering if there is any rough ETA on the release of this engine?

**Comment by AnkaChan** [comment]
It's gonna be released at 10/08

**Comment by chunleili** [comment]
> It's gonna be released at 10/08
So it is Nov 7th now, where is the code? ...^_^

**Comment by H-YWu** [comment]
It's 2024 Jun 14th now. Is the author too busy?

**Comment by AnkaChan** [comment]
I finally uploaded the code. I appreciate your patience
