### ISSUE TITLE
Cube stretching weird behavior with VBD

### ISSUE THREAD

**Issue by sin3point14** [AnkaChan/Gaia#11]
(This is a copy paste from the messages I dropped on discord a week ago: https://discord.com/channels/1232379741760127038/1232379841840549993/1260691237103599616)

Hey I was trying to setup some stress tests using gaia. I took the cubes supplied in the repo and tried stretching them a bit. I am getting some weird results, so I wanted to check if there is something wrong with my setup or this is a limitation of the algorithm/impementation
100 verts cube (Data\mesh_models\ModelsDifferentRes\Cube\Cube.t)
neohookean material
young's modulus = 1000
poisson's ration = 0.3,0.45,0.49,0.499,0.4995 respectively
vbd iterations = 20
timestep = 0.01666666
substeps = 1
We can see that the simulation gets worse 

https://github.com/user-attachments/assets/2621c197-ad75-4da5-b3aa-0e2487970b9b

https://github.com/user-attachments/assets/5b11e479-adee-4016-a45d-c30dad1c7e68

https://github.com/user-attachments/assets/4ac19930-55bd-41bc-af65-00153ee04b82

https://github.com/user-attachments/assets/c167cb21-8ba3-4fdf-885c-7213af0ac181

https://github.com/user-attachments/assets/002fbd43-2d1b-4714-97a6-1c8e521988f8

2577 verts cube (Data\mesh_models\ModelsDifferentRes\Cube\Cube_subdivided.t)
poisson's ratio = 0.3
all other params same
The simulation explodes and crashes

https://github.com/user-attachments/assets/14e50967-a741-41b7-bf83-0c52be636cc5

i changed substeps from 1 to 20 per frame
poisson's ratio = 0.3,0.45,0.49,0.499,0.4995
everything else the same
we see some weird behavior and crash in case of 0.3 and 0.45

https://github.com/user-attachments/assets/11351c51-6021-43ea-8070-56692eade10f

https://github.com/user-attachments/assets/1428e1af-11dd-400a-aa26-5de647058045

https://github.com/user-attachments/assets/b93c1385-ff45-44c9-9d61-5966ca21ec3e

https://github.com/user-attachments/assets/26956d75-8dd9-4f84-bffa-6a87c40bc274

https://github.com/user-attachments/assets/92a1b7f8-46a6-434c-9dfb-c98ee148621f

To help with the reproduction I forked and made a branch: https://github.com/sin3point14/Gaia/tree/stretch-cube .
this is the script to generate the scene: https://github.com/sin3point14/Gaia/blob/stretch-cube/Simulator/VBDDynamics/ParameterGen/High_Poisson_Ratio_Stretch_Test.py . To run it you'll need to change `machineName`. To change the cube model/poisson ratio change the lines I marked with `# <CHANGE THIS>`.
Or you can directly try running https://github.com/sin3point14/Gaia/tree/stretch-cube/Simulator/VBDDynamics/ParameterGen/Parameters/High_Poisson_Ratio_Stretch_Test
it contains the output of the committed version of the script

**Comment by AnkaChan** [comment]
Hi, sin3, it looks like you world bound is set to be 0-volume. This could be the issue.

**Comment by sin3point14** [comment]
I actually based my worldBounds on https://github.com/AnkaChan/Gaia/blob/main/Simulator/VBDDynamics/ParameterGen/Parameters/S01_Experiment_HybridModelsDrop_sequentiallyAppear/Test_64HybridModels_2steps_40Iters_stiff_Friction/Parameters.json#L68 . But changing it to `[-100, -100, -100], [100, 100, 100]` seems to have fixed the issue, thanks
