### ISSUE TITLE
RSA key issue with the submodules

### ISSUE THREAD

**Issue by korzen** [AnkaChan/Gaia#2]
Hi Anka,

Please consider changing the .submodules to
`[submodule "Simulator/3rdParty/cmake-git-version-tracking"]
	path = Simulator/3rdParty/cmake-git-version-tracking
	url = https://github.com/andrew-hardin/cmake-git-version-tracking.git

[submodule "Simulator/3rdParty/CuMatrix"]
	path = Simulator/3rdParty/CuMatrix
	url = https://github.com/AnkaChan/CuMatrix.git

[submodule "Simulator/3rdParty/MeshFrame2"]
	path = Simulator/3rdParty/MeshFrame2
	url = https://github.com/AnkaChan/MeshFrame2.git

[submodule "Simulator/3rdParty/oneTBB"]
	path = Simulator/3rdParty/oneTBB
	url = https://github.com/oneapi-src/oneTBB.git
`

I ran into RSA key issues with the current one

Thanks

**Comment by AnkaChan** [comment]
Changed. Thank you for pointing out!

**Comment by korzen** [comment]
Hi Anka, thanks for the update. However, the problem reappeared  due to`[submodule "Simulator/3rdParty/polyscope"]
	path = Simulator/3rdParty/polyscope
	url = git@github.com:AnkaChan/polyscope.git`

Cheers

**Comment by AnkaChan** [comment]
> Hi Anka, thanks for the update. However, the problem reappeared due to`[submodule "Simulator/3rdParty/polyscope"] path = Simulator/3rdParty/polyscope url = git@github.com:AnkaChan/polyscope.git`
> 
> Cheers

Hi korzen, thank you again for pointing out; it's fixed now
