### ISSUE TITLE
Missing header of "SoftBody.h"

### ISSUE THREAD

**Issue by DrChiZhang** [AnkaChan/Gaia#3]
Seems that SoftBody.h is included as #include "../SoftBody/SoftBody.h", while not released.

**Comment by AnkaChan** [comment]
That file should be deprecated a long time ago. Can you please provide me the name of the file that uses it? So I can remove the dependency.

**Comment by DrChiZhang** [comment]
PBD/Deformers/DeformerPuller.h 

BTW, have you ever try to build your code on Ubuntu OS?

**Comment by AnkaChan** [comment]
> PBD/Deformers/DeformerPuller.h
> 
> BTW, have you ever try to build your code on Ubuntu OS?

No. I may add compatibility to Linux & G++ in the near future
