### ISSUE TITLE
cloth simulation 

### ISSUE THREAD

**Issue by rossetti73** [AnkaChan/Gaia#4]
possible simulate also cloth ? like particole object ?

**Comment by AnkaChan** [comment]
Yes, I will provide a cloth simulator shortly; but it won't be an XPBD-based simulator. Instead, it will be using a novel simulator that surpasses XPBD in many ways. Hopefully, you will be able to see the new method in this year's Siggraph conference. Be excited.

**Comment by DrChiZhang** [comment]
> Yes, I will provide a cloth simulator shortly; but it won't be an XPBD-based simulator. Instead, it will be using a novel simulator that surpasses XPBD in many ways. Hopefully, you will be able to see the new method in this year's Siggraph conference. Be excited.

Looking forward to seeing your work. BTW, when the code will be released?

**Comment by rossetti73** [comment]
> novel simulator

 what type of technology is?  never heard of it before

**Comment by AnkaChan** [comment]
> > novel simulator
> 
> what type of technology is? never heard of it before

The simulator is novel... not that the method is called "novel"

**Comment by fire** [comment]
Would be interested to see if I can test cloth simulation on a rigid body "like a human character" for fitting purposes.

**Comment by AnkaChan** [comment]
> Would be interested to see if I can test cloth simulation on a rigid body "like a human character" for fitting purposes.

That is, (spoiler alert), the next update of Gaia, and a whole new research paper.
