### ISSUE TITLE
VBD.exe not responding 

### ISSUE THREAD

**Issue by TIAMAT-VFX** [AnkaChan/Gaia#8]
Could compile and build the VBD simulator, but when trying to  run an example with the suggested prompt I just do not get any response from the VBD.exe file, it will instead give me an error ONLY if I do not provide enough arguments while performing a request to run the simulator.
The only thing that was problematic in the process was having to manually place embree3.dll and tbb12.dll in the build directory.
I was using bash to clone the repo, the most recent version of Cmake, Visual studio 2019 ( as versions of 2022 after 17.0 do not support Cuda Toolkit previous to 12.3xxx and the requested version of CUDA toolkit is 11.xx), I
was using the suggested versions of Embree, Eigen3 (I could run tiny VBD sample), TBB.
I am trying to build again in a different environment, but I am confident that error/exceptions handling could be improved as the VBD.exe can apparently get into a state where it will give no response or feedback to the user.
Thanks for your work, I hope you find this useful.

**Comment by TIAMAT-VFX** [comment]
My hardware is RTX3080, AMD x5950, 128GB RAM, running Windows 10.

**Comment by AnkaChan** [comment]
Hi TIAMAT, it would be very helpful if you could share the logs. To keep the window after the program elapsed, you can open it using the command line prompt, instead of just double click it or using a .cmd/.bash file.

The most likely reason for this kind of errors is that the program cannot find the proper location of the models.json or parameters.json. Logs will show all those information.

**Comment by Peraspera1** [comment]
I met the same problem, my environment is windows11 RTX4060, CUDA12.4 and VS2022. My VS studio shows "physics.physicsParams().saveOutputs = false;" This line has triggered an exception: a write access permission conflict. GAIA::VBDPhysics::physicsParams(...)  Return nullptr, so replacing no Output with a custom path can simply solve this problem.
